---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  install:
    createNamespace: false
  values:
    # Immich version - required by the chart
    controllers:
      main:
        containers:
          main:
            image:
              tag: "v2.5.6"
            env:
              DB_HOSTNAME: immich-vectorchord-rw
              DB_PORT: "5432"
              DB_DATABASE_NAME: immich
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-user
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-user
                    key: password
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
