---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: immich-charts
  namespace: immich
spec:
  interval: 12h
  url: oci://ghcr.io/immich-app/immich-charts
  ref:
    tag: immich
