---
# Certificat wildcard pour les services publics
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bomal-cloud-wildcard
  namespace: default
spec:
  secretName: bomal-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.bomal.cloud"
  dnsNames:
    - "bomal.cloud"
    - "*.bomal.cloud"

---
# Certificat wildcard pour les services internes/locaux
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bomal-cloud-wildcard
  namespace: default
spec:
  secretName: local-bomal-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.local.bomal.cloud"
  dnsNames:
    - "local.bomal.cloud"
    - "*.local.bomal.cloud"
