apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.22.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
  releaseName: cnpg
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
