---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-user
  namespace: authentik
spec:
  encryptedData:
    password: AgB7gvo7L3lEOpJTSaiQrEOu4GcRcrK2p7xdCKo55yns3wAwtwBqSe9GRU9DD3j45sIVx8JPs/OBYQYaj75cNBOgY6rT7IXHbnfHsTExWTC8ru1osWKUW7Fb7DFpyPNBlu8nIk/l/JpfQSDC9niXZlTrsOS7CRfDovLlRCIH1I+mbBPkDWpy+cUvhEDIMciuNo7WWHPPJFUYrhB7cr555cc/fEcUqnb6mIohfGj5BSqRG8tMkZfb05UIu3iABHUPdQZXvNn1bw8GARpxThkOS6JUEEU5X667cnKaSaeulyqu0nSnVRqjRRy/ybOBjEFL/JzekRfpmqsTAP6JkAGGqPcMAFcRaEwWhSgZqkjqDEtPcP7S1CbyR80t8QBccEQJqJC67svjuz/rpnJIrU55kqGFDmuE9bBhVF9f5K6CXOkjlIa8MoDcRz8JZFQVsM49KaebQ+vUpO6ZR/5TjZB/AZ/nDwbFjT2vdSM/RLhaHBGVSEgSu9FbavA8dIwZ27z6RmUlRlLVLiIMYPD9h1v3nnXzkr5sxqyxQdkd3YCV48K+d0qBNPJan/tm2AnsOUtT7fr1WHPFtmlJlTjZvODtdHS1yXFrVnNgfY3zI7uGNeNGlEEqQAchaRciosGXkApUtqtz5FPutrvi57mZCeFlAcTsJuc1FZbLlAS9zJcVxkh+5nN44xYfaKPEuXNqttfjFGWEHKKEtTz3d+K2uUHAkO3NGuJ87EvWUyaULf0k+TasiojPMJXvP0hmDQmp2Q==
    username: AgB1oWWM+64QBBP2bNSiA9WlTr5q9ujFHC9QQpITmvnp2ubZTu70aCPpvt/whBCmrYqN6QZ44QeZJzoeQGFqwU6b01beA6nmQK8Aapwti9b7Z8S4Y9q5jk44QkM3lNAOcBgxpXOIPEND4PYS5Zyadt4cdRKyOllloNFZNMN9bpx4sPsWViZDriJCg+662BAx0SnvYtu0OK+oH2AFfBSz2MLWnuklMXGGCYvfK6SdoRFHogDYkulDDjGg+qmWeYPMpEozGPlGSVjBBggOCvKVy1ZYqEOJxLmClgGQ36nRz7K5lurBp8g2bslVZBApyVm1ScJnwI0ySr0wIWQVOouicZdBJdHPT7SUzlvJ+ncw3H+YHn9o9qMZdQDoWhOkyk24QQyr1CTbwiH9fJ9aPAvDOcFQXBsWNSZxFhVhjr+jQqakAKg70+JfedC3HQwekG8DH8gX62lvxrXlHk90rtMPe2aMYBt/hxMcKxNnrcqX+4n+xYrqxWIBdkFtjVar1NFKdkHyfsipj0igcjggEoiG3AvlyB5p5f18d5ZVXvuK4z0DqWb5qHixLjcwu3Ol4XAv6jBqSQgJEXQbRL4j9VPrlgvlCBfk5KOGOAxwRCucea5WDcd7qv2tMX8PlhymTPGNw6mzIfT8+CquZcqFkU2wXFJe/9l5ApA8mUFV5yDeu7nF7xatmn228VdrO7VYTFdMbGRLFA3hNXw/M0M=
  template:
    metadata:
      name: authentik-postgresql-user
      namespace: authentik
