---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      version: '2025.10.1'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgresql_password
      targetPath: authentik.postgresql.password
  values:
    authentik:
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-postgresql-rw
        port: 5432
        name: authentik
        user: authentik
    postgresql:
      enabled: false
    redis:
      enabled: true
